// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdrteyvcjubtplfcfsog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcnRleXZjanVidHBsZmNmc29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjQzODIsImV4cCI6MjA2NzE0MDM4Mn0._yY-BQfXn0uQblEZtc1xbE4PWfAKZ9DouZl_ZHzMhsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});